server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    resolver 127.0.0.11 ipv6=off valid=30s;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        set $php_upstream app:9000;
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }

    client_max_body_size 12M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
